spring:
  application:
    name: k12-edu-repo
  datasource:
    url: jdbc:mysql://192.168.0.2:3111/zdemo?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: roottest
    driver-class-name: com.mysql.cj.jdbc.Driver